---
- name: "Create superusers."
  become: true
  become_user: "{{ netbox_user }}"
  environment:
    DJANGO_SUPERUSER_USERNAME: "{{ item.username }}"
    DJANGO_SUPERUSER_EMAIL: "{{ item.email }}"
    DJANGO_SUPERUSER_PASSWORD: "{{ item.password | default(omit) }}"
  ansible.builtin.command:
    cmd: >
      {{ netbox_path }}/venv/bin/python3
      {{ netbox_path }}/netbox/manage.py
      createsuperuser --no-input
  register: "__netbox_superuser_creation"
  changed_when: "'Superuser created successfully' in __netbox_superuser_creation.stdout"
  failed_when:
    - "__netbox_superuser_creation.rc != 0"
    - "'That username is already taken' not in __netbox_superuser_creation.stderr"
  # no_log: true
  loop: "{{ netbox_superusers | default([]) }}"
  loop_control:
    label: "{{ item.username }}"
