---
- name: "Set platform/version specific variables."
  ansible.builtin.include_vars: "{{ __netbox_vars_file }}"
  loop: "{{ __netbox_vars_file_list }}"
  vars:
    __netbox_vars_file_list:
      - "OS-{{ ansible_facts['os_family'] }}.yml"
      - "OS-{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
      - "D-{{ ansible_facts['distribution'] }}.yml"
      - "D-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
      - "D-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    __netbox_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: "__netbox_vars_file is file"

- name: "Define netbox_system_packages."
  when: "netbox_system_packages is not defined"
  ansible.builtin.set_fact:
    netbox_system_packages: "{{ __netbox_system_packages | list }}"

- name: "Set vars for LDAP."
  when: "netbox_ldap_enabled | bool"
  ansible.builtin.set_fact:
    netbox_system_packages: "{{ netbox_system_packages + __netbox_ldap_system_packages }}"
    netbox_additional_python_requirements: "{{ netbox_additional_python_requirements + __netbox_ldap_python_packages }}"
