---
- name: "Install system dependencies."
  become: true
  ansible.builtin.package:
    name: "{{ netbox_system_packages }}"
    state: "present"

- name: "Download and extract archive."
  become: true
  ansible.builtin.unarchive:
    src: "{{ __netbox_url }}"
    dest: "/var/tmp"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: "0755"
    remote_src: true

- name: "Perform upgrade."
  when: "__netbox_upgrade_needed | default(false) | bool"
  become: true
  block:
    - name: "Stop services."
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: "stopped"
      loop:
        - "{{ netbox_service_name }}.service"
        - "{{ netbox_housekeeping_service_name }}.timer"
        - "{{ netbox_rq_service_name }}.service"

    - name: "Find files and directories to backup."
      ansible.builtin.find:
        path: "{{ netbox_path }}"
        patterns:
          - "media"
          - "scripts"
          - "reports"
          - "secret.key"
        file_type: "any"
      register: "__netbox_backup_files_dirs"

    - name: "Backup files and dirs for upgrade."
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "/var/tmp/netbox-{{ netbox_version }}/"
        owner: "{{ netbox_user }}"
        group: "{{ netbox_group }}"
        mode: "preserve"
        remote_src: true
      loop: "{{ __netbox_backup_files_dirs.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: "Delete old app folder."
      ansible.builtin.file:
        path: "{{ netbox_path }}"
        state: "absent"

- name: "Create application dir."
  become: true
  ansible.builtin.file:
    path: "{{ netbox_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: "0755"
    state: "directory"

- name: "Copy extracted archive into app folder."
  become: true
  ansible.builtin.copy:
    src: "/var/tmp/netbox-{{ netbox_version }}/"
    dest: "{{ netbox_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: "0755"
    remote_src: true
  notify:
    - "Run upgrade script."
    - "Restart services."
