---
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: postgres
    image: postgres:15-alpine
    pre_build_image: true
    groups:
      - sidecar
    env:
      POSTGRES_PASSWORD: "netbox123!"
      POSTGRES_USER: netbox
      POSTGRES_DB: netbox
    command: ""
    published_ports:
      - 5432:5432
    networks:
      - name: molecule
  - name: redis
    image: redis:7-alpine
    pre_build_image: true
    command: ""
    groups:
      - sidecar
    published_ports:
      - 6379:6379
    networks:
      - name: molecule
  - name: openldap
    image: bitnami/openldap:latest
    pre_build_image: true
    command: ""
    env:
      LDAP_ROOT: "DC=example,DC=org"
      LDAP_ADMIN_DN: "CN=admin,DC=example,DC=org"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - "${PWD}/molecule/ldap/bootstrap.ldif:/ldifs/50-bootstrap.ldif:ro"
    groups:
      - sidecar
    published_ports:
      - 1389:1389
    networks:
      - name: molecule

  - name: netbox
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-rockylinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 8000:8000
    networks:
      - name: molecule

provisioner:
  name: ansible
