---
- name: "Converge."
  hosts: "all,!sidecar"
  pre_tasks:
    - name: "Set Python path."
      when:
        - "ansible_os_family == 'RedHat'"
        - "ansible_distribution_major_version == '8'"
      ansible.builtin.set_fact:
        netbox_python_path: "/usr/bin/python3.11"

  roles:
    - role: "dschemp.netbox"
      become: true
      vars:
        netbox_db_host: "postgres"
        netbox_db_password: "netbox123!"
        netbox_redis_tasks_host: "redis"
        netbox_admins:
          - name: "Jane Doe"
            email: "jane.doe@example.com"
          - name: "John Doesnt"
            email: "john.doesnt@example.com"
        netbox_census_reporting_enabled: false
        netbox_listen_address: "0.0.0.0:8001"
        netbox_superusers:
          - username: "f_admin"
            email: "admin@example.org"
            password: "admin4life123!"
        netbox_user_shell: "/bin/bash"
        netbox_python_requirements: ["netbox-plugin-dns", "bleach"]
        netbox_plugins: ["netbox_dns"]
        netbox_force_upgrade_script: true
