---
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: postgres
    image: postgres:15-alpine
    groups:
      - sidecar
    env:
      POSTGRES_PASSWORD: "netbox123!"
      POSTGRES_USER: netbox
      POSTGRES_DB: netbox
    published_ports:
      - 5432:5432
  - name: redis
    image: redis:7-alpine
    groups:
      - sidecar
    published_ports:
      - 6379:6379

  - name: rockylinux8
    image: "geerlingguy/docker-rockylinux8-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: rockylinux9
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
