---
- name: Prepare environment.
  hosts: all
  tasks:
    - name: "TODO: Install Postgres."
      ansible.builtin.debug:
        msg: "TODO: Install Postgres."

    - name: "Install Redis (RedHat)."
      when: ansible_os_family == "RedHat"
      ansible.builtin.dnf:
        name: redis
        update_cache: true
        state: present

    - name: "Install Redis (Debian)."
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name: redis-server
        update_cache: true
        cache_valid_time: 3600
        state: present

    - name: "Start Redis."
      ansible.builtin.service:
        name: redis
        state: started
        enabled: true
